In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")

else:
  print("GPU not available. Using CPU")

GPU is available
Using GPU: Tesla T4


# Creating a Tensor

In [4]:
# using empty
x = torch.empty(2,3)
x

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31]])

In [5]:
# check type
type(x)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using once
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.9588, 0.6550, 0.8224],
        [0.8239, 0.7144, 0.9029]])

In [9]:
# use seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways

# arange
print("Using arange -->", torch.arange(0,10,2))

Using arange --> tensor([0, 2, 4, 6, 8])


In [14]:
# using linspace
print('Using linspace --> ', torch.linspace(0,10,10))

Using linspace -->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [15]:
# Using eye
print('Uisng eye --> ', torch.eye(5))

Uisng eye -->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [19]:
# Using full
print('Using full --> ', torch.full((3,3),5))
print('Using full --> ', torch.full((2,4),5))

Using full -->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
Using full -->  tensor([[5, 5, 5, 5],
        [5, 5, 5, 5]])


# Tensor Shapes

In [21]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
x.shape

torch.Size([2, 3])

In [23]:
torch.empty_like(x)

tensor([[135849698385280, 102157023436880,               0],
        [              0,               0,               0]])

In [24]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [28]:
# rand_like generate floats number so that's why use dtype=float
torch.rand_like(x , dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

# Tensor Data Types

In [29]:
# find data type
x.dtype

torch.int64

In [34]:
# assign data type
print(torch.tensor([1.0,2.0,3.0]))

# Change dtype float to int
print(torch.tensor([1.0,2.0,3.0] , dtype = torch.int32))

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [35]:
# Change int to float
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

In [38]:
# Using to()

x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


# Mathematical Operations

## 1. Scaler Operations

In [39]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [48]:
# Addition
print(x + 2)

# Subtraction
print(x - 2)

# Multiplication
print(x * 2)

# Division
print(x / 3)

# int division
print((x*2)//3)

# mod
print(((x*2)//3)%2)


# Power
print(x**2)

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])
tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])
tensor([[0.4478, 0.6047],
        [0.3568, 1.6477]])
tensor([[0.0746, 0.1008],
        [0.0595, 0.2746]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])


## Element wise operation

In [49]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [52]:
# add
print(a + b)
# sub
print(a - b)
# multiply
print(a * b)
# division
print(a / b)
# power
print(a ** b)
# mod
print(a % b)

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])
tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])
tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])
tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])
tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])
tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])


In [53]:
c = torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [54]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [55]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [56]:
d = torch.tensor([1.9,2.3,3.7,4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [57]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [59]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [60]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction operation

In [61]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [63]:
# sum
torch.sum(e)


tensor(28.)

In [64]:
# sum along columns
torch.sum(e, dim=0)

tensor([14., 11.,  3.])

In [65]:
# sum along rows
torch.sum(e, dim=1)

tensor([15., 13.])

In [68]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [69]:
# mean along rows
torch.mean(e, dim=1)

tensor([5.0000, 4.3333])

In [70]:
# median
torch.median(e)

tensor(4.)

In [73]:
# median along col
torch.median(e, dim=0)

torch.return_types.median(
values=tensor([5., 4., 0.]),
indices=tensor([0, 1, 1]))

In [72]:
# median along rows
torch.median(e, dim=1)

torch.return_types.median(
values=tensor([5., 4.]),
indices=tensor([0, 1]))

In [75]:
# min and max
print(torch.min(e))
print(torch.max(e))

tensor(0.)
tensor(9.)


In [76]:
# product
torch.prod(e)

tensor(0.)

In [77]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [78]:
# variance
torch.var(e)

tensor(9.8667)

In [79]:
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [80]:
# argmax to use find index of large value
torch.argmax(e)

tensor(3)

In [81]:
# argmin
torch.argmin(e)

tensor(5)

## 4. Matrix operation

In [85]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

In [86]:
print(f)
print(g)

tensor([[2, 6, 7],
        [7, 8, 3]])
tensor([[6, 1],
        [5, 5],
        [0, 4]])


In [87]:
# matrix multiplication
torch.matmul(f,g)

tensor([[42, 60],
        [82, 59]])

In [89]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [91]:
f

tensor([[2, 6, 7],
        [7, 8, 3]])

In [90]:
# transpose
torch.transpose(f, 0, 1)

tensor([[2, 7],
        [6, 8],
        [7, 3]])

In [92]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 8., 8.],
        [3., 3., 5.],
        [0., 6., 4.]])

In [93]:
# determinant
torch.det(h)

tensor(-6.)

In [94]:
# inverse
torch.inverse(h)

tensor([[ 3.0000, -2.6667, -2.6667],
        [ 2.0000, -2.0000, -1.5000],
        [-3.0000,  3.0000,  2.5000]])

## 5. Comparison operations

In [95]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 8, 4],
        [7, 2, 3]])
tensor([[8, 5, 6],
        [2, 9, 5]])


In [96]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j
# less than equal to
i <= j

tensor([[ True, False,  True],
        [False,  True,  True]])

## 6. Special functions

In [97]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 4., 2.],
        [7., 1., 1.]])

In [98]:
# log
torch.log(k)

tensor([[  -inf, 1.3863, 0.6931],
        [1.9459, 0.0000, 0.0000]])

In [99]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 5.4598e+01, 7.3891e+00],
        [1.0966e+03, 2.7183e+00, 2.7183e+00]])

In [100]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 5.4598e+01, 7.3891e+00],
        [1.0966e+03, 2.7183e+00, 2.7183e+00]])

In [101]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 2.0000, 1.4142],
        [2.6458, 1.0000, 1.0000]])

In [102]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9820, 0.8808],
        [0.9991, 0.7311, 0.7311]])

In [103]:
# relu
torch.relu(k)

tensor([[0., 4., 2.],
        [7., 1., 1.]])

In [106]:
# softmax
torch.softmax(k , dim=0)

tensor([[9.1105e-04, 9.5257e-01, 7.3106e-01],
        [9.9909e-01, 4.7426e-02, 2.6894e-01]])

## Inplace opeartions

In [107]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])
tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])


In [108]:
m.add_(n)

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [109]:
m

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [110]:
n

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [111]:
torch.relu(m)

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [112]:
m.relu_()

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [113]:
m

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

## Copying a Tensor

In [114]:
a = torch.rand(2,3)
a

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [115]:
b = a

In [117]:
b

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [118]:
a[0][0] = 0

In [119]:
a

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [120]:
b

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [121]:
id(a)

135845459641024

In [123]:
id(b)

135845459641024

In [124]:
b = a.clone()

In [125]:
a

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])